// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI29frJsA-D1F_onUyQD3w_iIskzpbCsk',
    appId: '1:99881619174:web:06ea96f7e84046488a7527',
    messagingSenderId: '99881619174',
    projectId: 'financiei-25512',
    authDomain: 'financiei-25512.firebaseapp.com',
    storageBucket: 'financiei-25512.firebasestorage.app',
    measurementId: 'G-8YQGM6LH2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXXi1JERd7HvSjn1NMj89XYUxiPWytYBY',
    appId: '1:99881619174:android:15c9788153e1f6828a7527',
    messagingSenderId: '99881619174',
    projectId: 'financiei-25512',
    storageBucket: 'financiei-25512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv5fqlwCsBO5l0mopX3LAQtd1sjTXrFNM',
    appId: '1:99881619174:ios:c8ef4d9cd62297a38a7527',
    messagingSenderId: '99881619174',
    projectId: 'financiei-25512',
    storageBucket: 'financiei-25512.firebasestorage.app',
    iosBundleId: 'com.example.flutterPersonalMoneyApp',
  );

}